## Preprocessing

In [148]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [149]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df=application_df.drop(columns=['EIN','NAME'])
#  YOUR CODE GOES HERE
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [150]:
# Determine the number of unique values in each column.

#  YOUR CODE GOES HERE

application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [151]:
# Look at APPLICATION_TYPE value counts for binning
app_type=application_df["APPLICATION_TYPE"].value_counts()
app_type

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [152]:
# Choose a cutoff value and create a list of application types to be replaced






# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE
app_remove = app_type.loc[app_type<=156]
application_types_to_replace=list(app_remove.index)
# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [153]:
application_df['APPLICATION_TYPE'].unique()

array(['T10', 'T3', 'T5', 'T7', 'T4', 'T6', 'Other', 'T19', 'T8'],
      dtype=object)

In [154]:
# Look at CLASSIFICATION value counts for binning
all_value=application_df["CLASSIFICATION"].value_counts()
#  YOUR CODE GOES HERE
all_value

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [155]:
# You may find it helpful to look at CLASSIFICATION value counts >1
i=all_value.loc[all_value>1]

#  YOUR CODE GOES HERE

i

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [156]:
type(i)

pandas.core.series.Series

In [157]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE
z=all_value.loc[all_value<1883]
# Replace in dataframe
classifications_to_replace=list(z.index)
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [158]:
application_df['CLASSIFICATION'].unique()

array(['C1000', 'C2000', 'C3000', 'C1200', 'Other', 'C2100'], dtype=object)

In [160]:
# Convert categorical data to numeric with `pd.get_dummies`
#  YOUR CODE GOES HERE

application_df=pd.get_dummies(application_df)
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [163]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE
y=application_df["IS_SUCCESSFUL"]
X=application_df.drop(columns="IS_SUCCESSFUL")
# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=78)

In [164]:
X_train.shape

(25724, 43)

In [165]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [166]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE

nn = tf.keras.models.Sequential()

# First hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=80, activation="relu", input_dim=43))
# Second hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=30, activation="relu"))
# Output layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=1,activation="sigmoid"))
# Check the structure of the model
nn.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_4 (Dense)             (None, 80)                3520

 dense_5 (Dense)             (None, 30)                2430

 dense_6 (Dense)             (None, 1)                 31

=================================================================
Total params: 5981 (23.36 KB)
Trainable params: 5981 (23.36 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [167]:
# Compile the model
#  YOUR CODE GOES HERE
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [168]:
# Train the model
#  YOUR CODE GOES HERE
nn.fit(X_train_scaled,y_train,epochs=50)

Epoch 1/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5709 - accuracy: 0.7233
Epoch 2/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5555 - accuracy: 0.7285
Epoch 3/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5531 - accuracy: 0.7315
Epoch 4/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5518 - accuracy: 0.7311
Epoch 5/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5498 - accuracy: 0.7318
Epoch 6/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5492 - accuracy: 0.7318
Epoch 7/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5483 - accuracy: 0.7332
Epoch 8/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5472 - accuracy: 0.7336
Epoch 9/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5470 - accuracy: 0.7338
Epoch 10/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5468 - accuracy: 0.7322
Epoch 11/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5459 - accuracy: 0.7351
Epoch 12/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5461 - accuracy: 0.7337
Epoch 13/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5451 - accuracy: 0.7352
Epoch 14/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5450 - accuracy: 0.7358
Epoch 15/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5447 - accuracy: 0.7367
Epoch 16/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5444 - accuracy: 0.7364
Epoch 17/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5437 - accuracy: 0.7367
Epoch 18/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5436 - accuracy: 0.7362
Epoch 19/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5433 - accuracy: 0.7370
Epoch 20/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5433 - accuracy: 0.7373
Epoch 21/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5431 - accuracy: 0.7358
Epoch 22/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5424 - accuracy: 0.7373
Epoch 23/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5422 - accuracy: 0.7369
Epoch 24/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5423 - accuracy: 0.7367
Epoch 25/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5419 - accuracy: 0.7376
Epoch 26/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5422 - accuracy: 0.7381
Epoch 27/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5418 - accuracy: 0.7373
Epoch 28/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7370
Epoch 29/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5414 - accuracy: 0.7383
Epoch 30/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5410 - accuracy: 0.7381
Epoch 31/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5414 - accuracy: 0.7379
Epoch 32/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5409 - accuracy: 0.7380
Epoch 33/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5406 - accuracy: 0.7378
Epoch 34/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5410 - accuracy: 0.7384
Epoch 35/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5405 - accuracy: 0.7386
Epoch 36/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5402 - accuracy: 0.7385
Epoch 37/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5405 - accuracy: 0.7396
Epoch 38/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5400 - accuracy: 0.7392
Epoch 39/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7396
Epoch 40/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5398 - accuracy: 0.7391
Epoch 41/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7382
Epoch 42/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5395 - accuracy: 0.7400
Epoch 43/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5395 - accuracy: 0.7384
Epoch 44/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5394 - accuracy: 0.7397
Epoch 45/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5392 - accuracy: 0.7385
Epoch 46/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5393 - accuracy: 0.7394
Epoch 47/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5389 - accuracy: 0.7395
Epoch 48/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5392 - accuracy: 0.7398
Epoch 49/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5388 - accuracy: 0.7399
Epoch 50/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5388 - accuracy: 0.7399

In [169]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5522 - accuracy: 0.7262 - 527ms/epoch - 2ms/step
Loss: 0.5521632432937622, Accuracy: 0.7261807322502136